# Generated by Django 3.2.8 on 2022-07-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('correo', models.CharField(max_length=255, verbose_name='correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='foto')),
            ],
        ),
    ]
